---
title: "Structural Topic Modelling of Avila"
author: "Isa Lykke Hansen"
date: "21/8/2017"
output: html_document
---

```{r setup, include=FALSE}

#Setup 

knitr::opts_chunk$set(echo = TRUE)

#wd <- "~/your/filepath/here/avila/" #NB change this working directory so it points to your local Avila folder!
wd <- "~/Dropbox/IMC/avila/"
setwd(wd) 

library(pacman)
p_load(stm, #for structural topic modelling
       Rtsne, #for determining number of topics
       geometry) #for determining number of topics

```

###Import and prepare data  
Imports the clean document term matrix and adds metadata to it  
Prepares the corpus for stm analysis
```{r}

load("data/avila_dtm") #import the clean dtm
dtm <- readCorpus(dtm, "slam") #convert the dtm to an stm-type corpus
meta <- read.csv(paste(wd, "/data/meta_data/metadata.csv", sep =''), sep = ";") #import the metadata
meta <- subset(meta, meta$format!="footnote") #make a subset of metadata that does not include footnotes
stm_data <- prepDocuments(dtm$documents, dtm$vocab, meta = meta, lower.thresh = 1) #add the metadata and remove terms that appear in only one document or less

```

###Structural Topic Model 
We build the models for inspection
```{r}

#search throuh different numbers of topics to find the ideal number for the simple model
#searchK(stm_data$documents, stm_data$vocab, K = c(5, 10, 15, 20, 25, 30, 35, 40), init.type = "Spectral")

#plain model (no metadata)
model_plain <- stm(documents = stm_data$documents, vocab = stm_data$vocab,
              K = 20,
              max.em.its = 75,
              init.type = "Spectral")


#build a model where we include metadata for the format (letter, book etc.)

#searchK(stm_data$documents, stm_data$vocab, K = c(5, 10, 15, 20, 25, 30, 35, 40), prevalence =~ format, data = stm_data$meta, init.type = "Spectral")

model_format <- stm(documents = stm_data$documents, vocab = stm_data$vocab,
              K = 25,
              prevalence = ~format,
              max.em.its = 500,
              data = stm_data$meta,
              init.type = "Spectral")

```

Create a model for year
```{r}

#to create a model for year we need to load a second dtm where we have excluded all the documents with NAs in the "year" column. We use the same prep-procedure as before:
load("data/avila_dtm_year")
dtm_year <- readCorpus(dtm_year, "slam")
meta_year <- read.csv(paste(wd, "/data/meta_data/metadata.csv", sep =''), sep = ";")
meta_year <- subset(meta, !is.na(meta$year) & meta$format!="footnote") #make a subset of metadata that does not include footnotes and docs with NAs in year
stm_data_year <- prepDocuments(dtm_year$documents, dtm_year$vocab, meta = meta_year, lower.thresh = 1)


searchK(stm_data_year$documents, stm_data_year$vocab, K = c(5, 10, 15, 20, 25, 30, 35, 40), prevalence =~ year, data = stm_data_year$meta_year, init.type = "Spectral")

model_year <- stm(documents = stm_data_year$documents, vocab = stm_data_year$vocab,
              K = 25,
              prevalence = ~year, #what to do about missing metadata?
              max.em.its = 500,
              data = year_data$meta,
              init.type = "Spectral")
```

#Model inspection  
Exploring the models with plots

```{r}
labelTopics(model_plain, c(3,7,20))
labelTopics(model_format, n=5)

plot(model_plain, type = "summary") #plot the estimated topic porportions
plot(model_format, type = "summary") #plot the estimated topic porportions

cloud(model_format) #wordclound for all topics
cloud(model_format, topic = 23) #wordcloud for specific topic

#estimate the effect of format on topic ?prevalance?
stm_data$meta$format <- as.factor(stm_data$meta$format)
prep <- estimateEffect(1:25 ~ format, model_format, meta = stm_data$meta, uncertainty = "Global")

#plot all levels of format for a specific topic
plot(prep, 
     "format", 
     topics = 5, 
     model = model_format, 
     printlegend = FALSE, 
     #xlab = "Time",
     xaxt = "n"
     )

#plot the difference between two topics
plot(prep, 
     covariate = "format", 
     topics = c(5, 23, 25),
     model = model_format, 
     method = "difference",
     cov.value1 = "letter", 
     cov.value2 = "book",
     xlab = "Books ... Letters",
     main = "Change in topic proportion from Letter to Book",
     xlim = c(-.3, .3))

#we see that topic 5 is strongly associated with letters, whereas topic 23 is more strongly associated with books

mod.out.corr <- topicCorr(model_format)
plot(mod.out.corr)

```

